export const PATH = {
  USERS: "/users",
  USER_ID: "/user/:id",
  EDIT_USER_ID: "/user/edit/:id",
  LOGIN: "/login",
  LOGOUT: "/logout",
  PRODUCTS: "/products",
  PRODUCT_ID: "/product/:id",
  EDIT_PRODUCT_ID: "/product/edit/:id",
  BRANDS: "/brands",
  BRAND_ID: "/brand/:id",
  EDIT_BRAND_ID: "/brand/edit/:id",
  ORDERS: "/orders",
  ORDER_ID: "/order/:id",
  EDIT_ORDER_ID: "/order/edit/:id",
};
